version: '3'

services:
  db:
    build:
      context: ./postgres  # Updated context to point to the postgres directory
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: andrew
      POSTGRES_PASSWORD: PooPoo1987!
      POSTGRES_DB: testdb
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "80:80"
    depends_on:
      - db
