# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Copy the PostgreSQL configuration file to the appropriate location
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Environment variables to initialize the PostgreSQL database and user
ENV POSTGRES_USER=andrew
ENV POSTGRES_PASSWORD=PooPoo1987!
ENV POSTGRES_DB=testdb

# This script will be executed when the container starts
COPY init-scripts/init-db.sh /docker-entrypoint-initdb.d/
