FROM postgres:latest

COPY postgresql.conf /etc/postgresql/postgresql.conf

ENV POSTGRES_USER=andrew
ENV POSTGRES_PASSWORD=PooPoo1987!
ENV POSTGRES_DB=testdb

COPY init-scripts/init-db.sh /docker-entrypoint-initdb.d/
