FROM python:3.8

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

EXPOSE 80

ENV POSTGRES_HOST=db
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB=testdb
ENV POSTGRES_USER=andrew
ENV POSTGRES_PASSWORD=PooPoo1987!

CMD ["python", "app.py"]
